### ISSUE TITLE
Mention MTA-STS regarding MX record security considerations

### ISSUE THREAD

**Issue by link2xt** [benbucksch/autoconfig-spec#3]
MTA-STS can be used to secure MX records, e.g. https://mta-sts.gmail.com/.well-known/mta-sts.txt contains `mx` records that are allowed to be in DNS.

This could be mentioned in relation to
https://github.com/benbucksch/autoconfig-spec/commit/335bd87bba671052a44ac7d1dfad69cde76f5210

**Comment by cketti** [comment]
Can you explain how MTA-STS would help in the context of autoconfig?

**Comment by benbucksch** [comment]
@link2xt The MX lookup is necessary to get decent detection rates. They need to stay in the spec. If we cannot rely on DNS, then our detection rates are very low. The spec describes multiple ways to mitigate this risk.

**Comment by benbucksch** [comment]
@link2xt @cketti
1. How widely is MTA-STS supported?

> MX records can be easily spoofed if they are requested by a client device via malicious Wi-Fi hotspot

The spec already mentions this risk and recommends to use DNS over HTTPS (DoH) to verify the MX records, to avoid such scenarios. What does MTA-STS add on top of that?

**Comment by benbucksch** [comment]
> Delta Chat we are not going to use DoH because we don't want any dependency on central servers such as Google/Cloudflare DoH in the client

To run the full autoconfig, you will need the ISPDB anyways, so you have a point of centralization anyways. You could use a DoH server of your own, or on the domain/owner of the ISPDB.

*How* you validate the MX entry is your own choice.

Indeed, it's maybe a good idea to add the MTA-STS in the same section where I mention DoH, as an alternative.

**Comment by mimi89999** [comment]
MTA-STS works similarly to HSTS. The other MTA first makes a DNS query and then caches the result.

Autoconfig will make the connection only once or very rarely, so there simply is no way to tell whether the server does support MTA STS.

**Comment by mimi89999** [comment]
BTW, why is doing MX queries over DoH mentioned, but SRV queries were rejected completely?

**Comment by benbucksch** [comment]
> https://mta-sts.gmx.com/.well-known/mta-sts.txt

This specifically is not really that helpful, because don't need the MX record to look up the ISP for gmx.com, because it's gmx.com. (And we have gmx.com in the ISPDB.) We need the MX specifically for customer domains of domain hosters, and they typically do *not* have MTA-STS. Indeed, not even gmx.biz (which is a gmx.net domain) has it: https://mta-sts.gmx.biz/.well-known/mta-sts.txt gives "host not found". So, for exactly those cases where we need the MX lookup, MTA-STS does not work, in current deployments, and is unlikely to work, due to the configuration overhead per customer domain. MTA-STS is exactly the same method as autoconfig, so if you set up MTA-STS, you might just as well also set up autoconfig.

I was about to add the following paragraph to section "DNS":

The MX server could be validated using MTA-STS, i.e.
https://mta-sts.%EMAILDOMAIN%/.well-known/mta-sts.txt
However, that is not widely deployed on customer domains,
therefore limiting its usefulness.

But I really doubt it would help anything in practice to make that additional call. In exactly the cases where we need it, it's not deployed.

**Comment by benbucksch** [comment]
> BTW, why is doing MX queries over DoH mentioned, but SRV queries were rejected completely?

That's offtopic here, and it's a FAQ, so I wrote #4 for that.

**Comment by benbucksch** [comment]
> Unless we have a list of existing providers which don't have autoconfig XML but have SRV records, adding this does not help.

Exactly.

**Comment by benbucksch** [comment]
> MX record lookup is optional

Actually, the MX record lookup is central to the autoconfig protocol. To fully support the protocol, and to get decent detection rates, the MX lookup is needed.

The result is: If you're concerned about DNS spoofing, you can use your own DoH server or that of the ISPDB to validate the results. The spec also mentiones multiple other mitigations of this risk. The combination works reasonably well.

**Comment by benbucksch** [comment]
That's of course up to you, yes. I understand that your usecase is different.

**Comment by benbucksch** [comment]
See section 4, last paragraph. (Many of the questions are already answered in the spec.)
https://benbucksch.github.io/autoconfig-spec/draft-autoconfig-1.html#name-config-retrieval-for-mail-c
